# Generated by Django 5.0 on 2023-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_jobseekerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='media/resumes'),
        ),
    ]
