# Generated by Django 5.0 on 2023-12-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_job_model_apply_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_model',
            old_name='apply_at',
            new_name='update_at',
        ),
    ]
